<x-layouts.passenger title="Isi Data Penumpang - PO. Akas">
<main class="flex-grow w-full max-w-container-max mx-auto px-gutter py-md md:py-lg flex flex-col items-center"><div class="w-full max-w-3xl"><div class="mb-md"><h1 class="text-h1-mobile md:text-h1 font-h1-mobile md:font-h1 text-on-surface mb-sm">Detail Penumpang</h1><p class="text-body text-on-surface-variant">Lengkapi data penumpang untuk jadwal {{ $schedule->busRoute->originCity->name }} - {{ $schedule->busRoute->destinationCity->name }}.</p></div>
<form class="space-y-md" method="POST" action="{{ route('booking.passengers.store') }}">@csrf
@foreach($selectedSeats as $index => $seat)
<div class="bg-surface-container-lowest rounded-xl border border-outline-variant shadow-sm overflow-hidden"><div class="bg-surface-container-low px-md py-sm border-b border-outline-variant flex items-center justify-between"><h2 class="text-h3 font-h3 text-on-surface flex items-center gap-2"><span class="material-symbols-outlined text-primary">person</span>Penumpang {{ $index + 1 }}</h2><div class="bg-primary-container text-on-primary px-3 py-1 rounded-full text-caption font-caption font-bold">Kursi {{ $seat['seat_number'] }}</div></div><div class="p-md space-y-md"><label class="block"><span class="block text-label-form font-label-form text-on-surface mb-base">Nama Lengkap</span><input class="w-full rounded-lg border-outline-variant bg-surface" name="passengers[{{ $index }}][name]" value="{{ $index === 0 ? auth()->user()->name : '' }}" required></label><div class="grid grid-cols-1 md:grid-cols-2 gap-md"><label class="block"><span class="block text-label-form font-label-form text-on-surface mb-base">Nomor HP</span><input class="w-full rounded-lg border-outline-variant bg-surface" name="passengers[{{ $index }}][phone]" value="{{ $index === 0 ? auth()->user()->phone : '' }}" required></label><label class="block"><span class="block text-label-form font-label-form text-on-surface mb-base">No. Identitas <span class="text-caption text-outline">(Opsional)</span></span><input class="w-full rounded-lg border-outline-variant bg-surface" name="passengers[{{ $index }}][id_number]"></label></div></div></div>
@endforeach
<div class="flex justify-between pt-md"><a class="px-md py-sm border border-outline-variant rounded-lg text-primary" href="{{ route('schedules.seats', $schedule) }}">Kembali</a><button class="px-md py-sm bg-primary text-on-primary rounded-lg font-label-form text-label-form">Lanjut ke Konfirmasi</button></div>
</form></div></main>
</x-layouts.passenger>
